jobs:
    deploy:
          runs-on: ubuntu-latest
                steps:
                        - name: Check SSH Client Version
                                  run: |
                                              which ssh
                                                        ssh -V

